---
scale_storage:
  - filesystem: gpfs01
    disks:
      - device: /dev/vdb
        nsd: nsd1
        servers: scale01
        failureGroup: 1
        usage: dataAndMetadata
        pool: system
      - device: /dev/vdc
        nsd: nsd2
        servers: scale01
        failureGroup: 1
        usage: dataOnly
        pool: silver

scale_cluster_manager: true
